### ISSUE TITLE
Not good repo name

### ISSUE THREAD

**Issue by KendallDoesCoding** [nairvarun/nairvarun.github.io#1]
@nairvarun Idk if you know this, but Github has a special feature that if your repo name is your username, the README.md file will display on your profile. So, if you ever make a README on this repo, it will display on your profile even though its of no relevance. So what I suggest is, you display a custom readme with what you code, what languages you know/are learning which will display on your profile and change this repo name to something like nairvarun-portfolio if that's what this is :)

**Comment by KendallDoesCoding** [comment]
Like, if you go to my profile, you will see this. 

![image](https://user-images.githubusercontent.com/84712013/147494607-5e41e984-462a-4f8d-8b45-370462120a16.png)

**Comment by KendallDoesCoding** [comment]
@nairvarun Thanks for changing the repo name. Closing this now

**Comment by nairvarun** [comment]
yupp. thanks for the heads up meaning

**Comment by KendallDoesCoding** [comment]
> yupp. thanks for the heads up meaning

yeah, i saw this repo on my dashboard and i was like, well then he wont be able to create a README.md if you ever want to for this project.
