### ISSUE TITLE
[FEATURE REQUEST] Email change

### ISSUE THREAD

**Issue by KendallDoesCoding** [nairvarun/nairvarun.github.io#2]
Hi, 

Right now, your using ProtonMail, but you can make a github pages email too.

Check this out - https://www.kristasimmons.io/blog/custom-email-domain-github-pages/

**Comment by KendallDoesCoding** [comment]
Zoho and yandex are free, but for now obviously ProtonMail is all well and good, but this is just a suggestion to make the email be a little professional :)

**Comment by KendallDoesCoding** [comment]
Closing because I think you can only do this if you linked your custom domain to Github Pages and hosting stuff from there.

Sorry

**Comment by nairvarun** [comment]
wow. i was looking for something like this but i couldn't find anything. rn i'm just testing things here but this will be very helpful when i get a proper domain.

thanks a lot

**Comment by KendallDoesCoding** [comment]
> wow. i was looking for something like this but i couldn't find anything. rn i'm just testing things here but this will be very helpful when i get a proper domain.
> 
> thanks a lot

yes it will, and ig you can even use something like the gmail smtp to send emails from that domain. Which is what I'm doing rn.

your welcome :)

**Comment by KendallDoesCoding** [comment]
@nairvarun I just sent you a email on that protonmail email listed on this site from my custom domain email just so you can see what i mean, i use the gmail smtp and [improvmx](https://improvmx.com/)

**Comment by nairvarun** [comment]
yupp. got it. i'll make sure to remember improvmx
