### ISSUE TITLE
Not responsive on Mobile

### ISSUE THREAD

**Issue by KendallDoesCoding** [nairvarun/nairvarun.github.io#2]
The education and mail on the website is NOT responsive on Mobile: 
![image](https://user-images.githubusercontent.com/84712013/200562202-ff0279bd-33ee-45eb-b6d2-c9e20c260129.png)

**Comment by nairvarun** [comment]
is it better now?

**Comment by KendallDoesCoding** [comment]
Yes! Thanks.

**Comment by KendallDoesCoding** [comment]
Yes! Thanks.
