### ISSUE TITLE
[BUG] Link not working

### ISSUE THREAD

**Issue by KendallDoesCoding** [nairvarun/nairvarun.github.io#4]
the "oybt" button is not working.

![image](https://user-images.githubusercontent.com/84712013/204096016-61946870-2497-406a-b3a2-8af65373cfa0.png)

**Comment by nairvarun** [comment]
i aware. it's not supposed to do anything for now.

**Comment by KendallDoesCoding** [comment]
> i'm aware. it's not supposed to do anything for now.

Ok!
